### ISSUE TITLE
Addon prevents queing for random battleground

### ISSUE THREAD

**Issue by YouTubeNATE** [Exupery/DontCast#8]
I had to dissable DontCast in order to que for random battlegrounds.

**Comment by YouTubeNATE** [comment]
DontCast has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI.  [Disable] [Ignore].  I can't que for battlegrounds without this addon Disabled.

**Comment by Exupery** [comment]
Sorry, for some reason never received a notification about this issue, but should have been resolved by 1ff1b0a94aa6ae4e743a6510f3a44a5f27d16a4e
